/**
 * Generated Theme
 * 
 * This file is auto-generated by the theme generator.
 * It will be replaced when a new game is generated.
 * 
 * For development/testing, this contains a default theme.
 */

export interface ThemeColors {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  backgroundAlt: string;
  player: string;
  obstacle: string;
  collectible: string;
  enemy: string;
  text: string;
  textSecondary: string;
  success: string;
  danger: string;
  warning: string;
  overlay: string;
  overlayDark: string;
}

export interface ThemeTypography {
  fontFamily: string;
  fontFamilyBold: string;
  fontSize: {
    tiny: number;
    small: number;
    medium: number;
    large: number;
    huge: number;
    title: number;
  };
  fontWeight: {
    normal: string;
    bold: string;
    black: string;
  };
  letterSpacing: {
    tight: number;
    normal: number;
    wide: number;
  };
}

export interface ThemeAnimations {
  duration: {
    instant: number;
    fast: number;
    normal: number;
    slow: number;
  };
  easing: {
    default: string;
    sharp: string;
    smooth: string;
    bounce: string;
  };
  style: {
    transitionSpeed: 'instant' | 'fast' | 'normal' | 'slow';
    preferredEasing: 'default' | 'sharp' | 'smooth' | 'bounce';
  };
}

export interface ThemeLayout {
  spacing: {
    tiny: number;
    small: number;
    medium: number;
    large: number;
    huge: number;
  };
  borderRadius: {
    none: number;
    small: number;
    medium: number;
    large: number;
    round: number;
  };
  shadow: {
    none: string;
    small: string;
    medium: string;
    large: string;
  };
}

export interface ThemeEffects {
  particles: {
    enabled: boolean;
    density: 'low' | 'medium' | 'high';
    colors: string[];
  };
  screenShake: {
    enabled: boolean;
    intensity: 'subtle' | 'medium' | 'strong';
  };
  background: {
    parallax: boolean;
    gradient: boolean;
    animated: boolean;
  };
}

export interface Theme {
  colors: ThemeColors;
  typography: ThemeTypography;
  animations: ThemeAnimations;
  layout: ThemeLayout;
  effects: ThemeEffects;
}

/**
 * Default theme for development
 * This will be replaced by the generated theme
 */
export const theme: Theme = {
  colors: {
    primary: '#FF3366',
    secondary: '#FF6B35',
    accent: '#FFD23F',
    background: '#1A1A1D',
    backgroundAlt: '#4E4E50',
    player: '#00E5FF',
    obstacle: '#FF00AA',
    collectible: '#FFD23F',
    enemy: '#FF3366',
    text: '#FFFFFF',
    textSecondary: '#CCCCCC',
    success: '#4CAF50',
    danger: '#F44336',
    warning: '#FF9800',
    overlay: 'rgba(0, 0, 0, 0.5)',
    overlayDark: 'rgba(0, 0, 0, 0.8)'
  },
  typography: {
    fontFamily: 'System',
    fontFamilyBold: 'System',
    fontSize: {
      tiny: 10,
      small: 14,
      medium: 18,
      large: 24,
      huge: 36,
      title: 48
    },
    fontWeight: {
      normal: '400',
      bold: '700',
      black: '900'
    },
    letterSpacing: {
      tight: -0.5,
      normal: 0,
      wide: 1.5
    }
  },
  animations: {
    duration: {
      instant: 100,
      fast: 200,
      normal: 300,
      slow: 500
    },
    easing: {
      default: 'ease',
      sharp: 'ease-in-out',
      smooth: 'cubic-bezier(0.4, 0.0, 0.2, 1)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)'
    },
    style: {
      transitionSpeed: 'fast',
      preferredEasing: 'sharp'
    }
  },
  layout: {
    spacing: {
      tiny: 4,
      small: 8,
      medium: 16,
      large: 24,
      huge: 40
    },
    borderRadius: {
      none: 0,
      small: 8,
      medium: 16,
      large: 24,
      round: 9999
    },
    shadow: {
      none: 'none',
      small: '0 2px 4px rgba(0, 0, 0, 0.1)',
      medium: '0 4px 8px rgba(0, 0, 0, 0.2)',
      large: '0 8px 16px rgba(0, 0, 0, 0.3)'
    }
  },
  effects: {
    particles: {
      enabled: true,
      density: 'high',
      colors: ['#FF3366', '#FF6B35', '#FFD23F']
    },
    screenShake: {
      enabled: true,
      intensity: 'strong'
    },
    background: {
      parallax: false,
      gradient: true,
      animated: true
    }
  }
};

// Convenience accessors
export const colors = theme.colors;
export const typography = theme.typography;
export const animations = theme.animations;
export const layout = theme.layout;
export const effects = theme.effects;

// Helper functions
export function spacing(size: 'tiny' | 'small' | 'medium' | 'large' | 'huge'): number {
  return layout.spacing[size];
}

export function borderRadius(size: 'none' | 'small' | 'medium' | 'large' | 'round'): number {
  return layout.borderRadius[size];
}

export function duration(speed: 'instant' | 'fast' | 'normal' | 'slow'): number {
  return animations.duration[speed];
}

export function fontSize(size: 'tiny' | 'small' | 'medium' | 'large' | 'huge' | 'title'): number {
  return typography.fontSize[size];
}

export default theme;
